name: Build Candidate

# Controls when the workflow will run
on:
  # Triggers the workflow only on push to the main branch (and temorarily to branch that is introducing it)
  push:
    branches:
      - main
      - ci-build-pipeline-110

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          pip install https://download.splunk.com/misc/packaging-toolkit/splunk-packaging-toolkit-1.0.1.tar.gz

      - name: Set patch version
        run: |
          patch=$(TZ=UTC0 git show -s --date=format-local:'%Y%m%d%H%M' --format=%cd)
          echo "Patch version is $patch"
          sed -ri "s/\"version\": \"([0-9]+\\.[0-9]+)\\.[0-9]+\"/\"version\": \"\\1.$patch\"/" app/redhat_insights/app.manifest
          sed -ri "s/version = ([0-9]+\\.[0-9]+)\\.[0-9]+/version = \\1.$patch/" app/redhat_insights/default/app.conf

      - name: Create package
        run: |
          mkdir build
          slim package app/redhat_insights -o build/

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: redhat-insights-splunk
          path: build/*
